### ISSUE TITLE
Add estimation and probabilty of risks in risk analysis and a Impact probality matrix

### ISSUE THREAD

**Issue by ds161833** [Data-Boom/SOEN490#1]
Finish up proposal

Comment from the professor:
"Risk Analysis: There is no estimation for the impact and probability of each identified risk. You also need to add the Impact-Probability Matrix, as we did for SOEN 390"

- [x] estimation for the impact for each identified risk
- [x] probability of each identified risk
- [x] Impact-Probability Matrix

**Comment by Mehrdadmaskull** [comment]
Thanks @ratulkai93 and @ds161833 

We have a Testing Plan document that will be further improved when we start the development of the project.

This story is good to be closed
