### ISSUE TITLE
unable to overwrite my-db folder 

### ISSUE THREAD

**Issue by JeremiahTee** [Data-Boom/SOEN490#107]
**Describe the bug**
Because of the way we persist data in Database.ts, the my-db folder that is created initially when running _docker-compose up_ for the first time, cannot be overwritten. 
This is because of the _.save_ method that needs to be changed. For ex. line 39
` await connection.manager.save(pubTypeError);`
Instead of using _.save_ , we should find a way to add to the existing DB or update it.

**To Reproduce**
1. Set up development environment.
2. Attempt to add data to db.
3. Realize nothing happens.

**Expected behavior**
The db should be updatable.

**Additional info**

Deleting the my-db file before running _docker-compose up_ again after any change. 
Just saving the db, causes issues if you have already instantiated the DB. That is why we need to delete the "my-db" folder every time before running docker-compose up. 

Possible solution: use a custom query builder that inserts

**Comment by TiraFire** [comment]
No longer required due to the fact that we had changed to an online DB (Azure) and therefore this was a problem with a local DB which we no longer use.
