### ISSUE TITLE
User Personas

### ISSUE THREAD

**Issue by lposo** [Data-Boom/SOEN490#11]
As a developer, I would like to have user personas that can aid in focusing on what the target audience of the project desires.

**Description:** When planning a project, it is important to understand the types of individuals that may use the product being designed. Thus, user personas can be used to incorporate a user's needs and goals, while avoiding things that would frustrate them.

**Tasks Involved**

- [x] Creation of at least 2 user personas.

- [x] Creation of graphics displaying the user personas.

**Comment by lposo** [comment]
User Personas: https://drive.google.com/drive/u/1/folders/1cXa706IqVBqqvUh6HCMq9UEDciz_Odxz

**Comment by Mehrdadmaskull** [comment]
Ready to be closed.
Thanks @lposo
