### ISSUE TITLE
AT-1 Graph Feature Acceptance Test

### ISSUE THREAD

**Issue by Mehrdadmaskull** [Data-Boom/SOEN490#110]
##### Here there are all tests needed for this feature

Graph epic consists of sub-stories that were mostly implemented

Tests | Variable Inputs | Expected Result | Status 
---|---|--|---
Access the home page | Launch the website on a localhost|Homepage is shown with the design based on the mock-ups|----
Access the graph page | Navigate to the graph from the side menu | The graph page appears | ----
View a dataset | Click on the "load a dataset" to load a sample dataset | A sample dataset should appear | ----
Hide a dataset | Click the "eye" icon next a dataset on the graph legend | The corresponding dataset disappears and the "eye" icon changes | ----
Unhide a dataset | Click the "closed eye" icon next a dataset on the graph legend | The corresponding dataset appears and the "eye" icon changes | ----
Change x/y scale | Click the "CHANGE X/Y SCALE" | The x/y scale changes from log to ln, or ln to log | ----
Delete Dataset |  Select a dataset via dropdown and click on delete dataset | The appropriate dataset is removed from the graph and legend, the list is updated | ----
Zoom in/out |  Scroll in/out | Scroll in zooms in, scroll out zooms out | ----

##### Demo Steps

User must first launch the website on their localhost by visiting [http://localhost:45000/](http://localhost:45000/)
Then they must click on the side-bar menu on the navigation bar and then click on Graph
Once they are navigated to the graph page, they will be able to see all the features for the current release
- User clicks on the "load a dataset" button
- User clicks the "eye" icon next to a dataset in the legend
- User clicks on the new "eye" icon next to a dataset in the legend
- User clicks the CHANGE X SCALE.
- User clicks the CHANGE X SCALE.
- User clicks the CHANGE Y SCALE.
- User clicks the CHANGE Y SCALE.
- User selects a dataset from the dropdown list and clicks delete.
- User scrolls in.
- User scrolls out.

**Comment by cbkiyanda** [comment]
Tests | Variable Inputs | Expected Result | Status
-- | -- | -- | --
Access the home page | Launch the website on a localhost | Homepage is shown with the design based on the mock-ups | ACCEPTED
Access the graph page | Navigate to the graph from the side menu | The graph page appears | ACCEPTED. Note: Below the banner, on the main page, can the words Graphs, Downlods, etc be links?
View a dataset | Click on the "load a dataset" to load a sample dataset | A sample dataset should appear | WORKS. Display quirk that needs to be fixed. See following comment.
Hide a dataset | Click the "eye" icon next a dataset on the graph legend | The corresponding dataset disappears and the "eye" icon changes | ACCEPTED
Unhide a dataset | Click the "closed eye" icon next a dataset on the graph legend | The corresponding dataset appears and the "eye" icon changes | ACCEPTED
Change x/y scale | Click the "CHANGE X/Y SCALE" | The x/y scale changes from log to ln, or ln to log | WORKS. The option label working is ambiguous. The placement adds to the ambiguity. See further comment.
Delete Dataset | Select a dataset via dropdown and click on delete dataset | The appropriate dataset is removed from the graph and legend, the list is updated | ACCEPTED
Zoom in/out | Scroll in/out | Scroll in zooms in, scroll out zooms out | WORKS. Zoom in out should be controllable independently for x and y axes, i.e. I would like to scroll y axis without touching the x axis and conversely.

**Comment by cbkiyanda** [comment]
Overlay menus need an X button or a Cancel/Close button. Getting out of this menu is done (I found out) by clicking besides it. The functionality is hidden. Needs to be more obvious.
![Screenshot from 2020-12-09 14-27-58](https://user-images.githubusercontent.com/454918/101678500-031aeb80-3a2c-11eb-8469-533fb1fd276e.png)

**Comment by cbkiyanda** [comment]
When reducing window size, there's an overlay between the dataset names and the graph. This shouldn't happen. Too much white space in the dataset label.

There's also a disconnect between the legend on the graph (dataset 1, dataset 2, dataset 3) and the dataset names on the right.  If you move (1) the hide/unhide (eye) icon next to the delete icon and (2) the point label (red dot, blue dot, etc) to the list of datasets, you can get rid of the legend in the plot.

![Screenshot from 2020-12-09 14-29-43](https://user-images.githubusercontent.com/454918/101678612-2b0a4f00-3a2c-11eb-8595-423d4227bc89.png)

**Comment by cbkiyanda** [comment]
The change x scale button is ambiguous. Scientists usually understand x scale to mean the numerical extent (1 to 10, 0 to 5, etc). See the attached screenshot for a strong suggestion of the desired look. Put a button at the end of each axis. The button reads 'log' when the axis is linear. Clicking the button switches the axis to log scale and the button then reads 'lin' while the axis is in log scale. In other words, the button gives you the action you will get when clicking.

![loglin](https://user-images.githubusercontent.com/454918/101679280-22664880-3a2d-11eb-957f-d968f9a36281.png)

**Comment by TiraFire** [comment]
@cbkiyanda We modified the Graph page a lot, I will go over the new graph with you this week. All the issues have been address but the change from D3 to the new graphing library removed the functionality for the ln-log scale (It will be reimplemented in the following sprint. I will create another AT for you to go through with the new functionality of the Graph page.
