### ISSUE TITLE
AT-2 Upload File Acceptance Test

### ISSUE THREAD

**Issue by TiraFire** [Data-Boom/SOEN490#111]
##### Here there are all tests needed for this feature

Tests | Variable Inputs | Expected Result | Status 
---|---|--|---
Access the home page | Launch the website on a localhost|Homepage is shown with the design based on the mock-ups|----
Access the Upload A File page | Navigate to page from the side menu | The Upload A File page appears | ----
Choose A File | Click on the "Choose File" | File Browser appears to choose a file | ----
Upload file | Click the "Upload this file!" button | The file uploads | ----

##### Demo Steps

User must first launch the website on their localhost by visiting [http://localhost:45000/](http://localhost:45000/)
Then they must click on the side-bar menu on the navigation bar and then click on "Upload a File"
- Click on the "Choose File" and select file
- Click the "Upload this file!" button
- Verify in the database that it exists

**Comment by cbkiyanda** [comment]
Tests | Variable Inputs | Expected Result | Status
-- | -- | -- | --
Access the home page | Launch the website on a localhost | Homepage is shown with the design based on the mock-ups | ACCEPTED
Access the Upload A File page | Navigate to page from the side menu | The Upload A File page appears | ACCEPTED
Choose A File | Click on the "Choose File" | File Browser appears to choose a file | ACCEPTED
Upload file | Click the "Upload this file!" button | The file uploads | Clicking the "UPLOAD THIS FILE!" button does not give any feedback that a file is uploading. I can't confirm this is happening. Also, the button label is a little dramatic. A simple "Upload" would be enough.

**Comment by TiraFire** [comment]
With the new requirements from our last couple talks, I will make a new acceptance test for this feature as well with the new functionality joining this feature with the manual upload. @cbkiyanda
