### ISSUE TITLE
DB Initial Setup [References: #2]

### ISSUE THREAD

**Issue by silent-po2** [Data-Boom/SOEN490#12]
As a Developer, I would like to have a database for storing and accessing data

Description: This is the portion for the database's first steps. This covers everything from the initial setup, the tables and queries proper, and other relevant functions.  

Tasks Involved:

    Backend
    Unit Test

Mockup Image or link to Mockup:

To Come.

Story Point - TBD
RIsk - TBD
Priority - TBD

**Comment by Mehrdadmaskull** [comment]
In the next sprint, we will need to verify the database entities with the data model from the architecture user story.
Story is good to be closed
