### ISSUE TITLE
Saved Data

### ISSUE THREAD

**Issue by JeremiahTee** [Data-Boom/SOEN490#14]
As a user, I would like to access my saved/favourited data.

**Description**: 
This is a task pertaining the the User page #13. This is that part where the user can see their favorited datasets and/or graphs as well as access the original graph or dataset via link.

**Tasks Involved:**

- [x] Visual Table of Saved Datasets/Graphs #139
- [x] Endpoint to load the appropriate data in the table #140
- [x] Unit Test
- [x] UI Test

![image](https://user-images.githubusercontent.com/25015601/100808864-f16d8e80-3402-11eb-83cc-0ce51f96dbc1.png)

**Acceptance Criteria**
- Unit tests must test the fetching of appropriate datasets, and UI tests on the links and scroll completed.
- Visually appealing table displayed with the correct datasets/graphs
- Functional links to graph or search page (depending on saved graph or dataset)

Story Point - TBD
RIsk - Low
Priority - Medium

**Comment by Mehrdadmaskull** [comment]
This issue will be closed as the UI tests for this part has been done in #243
