### ISSUE TITLE
[Backend] - Endpoint to load User Details in User Page

### ISSUE THREAD

**Issue by TiraFire** [Data-Boom/SOEN490#145]
As a developer, I would like send a query consisting of the account users unique identifier (Email) to retrieve their user details 
(Name (first and last), D.O.B, and Organization)

**Tasks Involved:**

- [x] Creating an endpoint accessible from frontend

**Acceptance Criteria:**
Should send a GET requests to a localhost:4000/User and retrieve found details (Name (first and last), D.O.B, Email, and Organization) back in .json format

**Risk** - High
**Priority** - High

**Comment by GD-Dheer** [comment]
This is on the user profile? If so, this can also leverage authentication apis I am doing to easily do this story @TiraFire

**Comment by GD-Dheer** [comment]
Will assist as this story
