### ISSUE TITLE
[Backend] - Endpoint to Save Changed User Details in User Page

### ISSUE THREAD

**Issue by TiraFire** [Data-Boom/SOEN490#146]
As a developer, I would like send a query consisting of the account users unique identifier and a new user detail (Name (first and last), D.O.B, and Organization, Password) and have it updated in the database.

**Tasks Involved:**

- [x] Creating an endpoint accessible from frontend

**Acceptance Criteria:**
Should send a POST request to a localhost:4000/User and update the new information

**Risk** - High
**Priority** - High

**Comment by GD-Dheer** [comment]
> As a developer, I would like send a query consisting of the account users unique identifier and a new user detail (Name (first and last), D.O.B, and Organization, Password) and have it updated in the database.
> 
> **Tasks Involved:**
> 
> * [ ]  Creating an endpoint accessible from frontend
> 
> **Acceptance Criteria:**
> Should send a POST request to a localhost:4000/User and update the new information
> 
> **Risk** - High
> **Priority** - High

What is this unique identifier? Is this updating the User Information on User Profile? If so, this ticket can leverage to authentication Services to easily do this. @TiraFire 

Also maybe not all info should be modifiable - arent these people researchers? If they want to update their names, dob why not make a new account. This should not be allowed
