### ISSUE TITLE
Uploaded Data View

### ISSUE THREAD

**Issue by JeremiahTee** [Data-Boom/SOEN490#15]
As a user, I would like to access my uploaded data.

**Description**: 
This is a task pertaining the the User page #13. This is that part where the user can see their uploaded datasets as well as access the dataset via link.

**Tasks Involved:**

- [x] Visual Table of Uploaded Datasets #142
- [x] Endpoint to load the appropriate data in the table #143
- [x] Unit Test 
- [x] UI Test

![image](https://user-images.githubusercontent.com/25015601/100821134-c04e8780-341d-11eb-9020-40f18e0f14c2.png)

**Acceptance Criteria**
- Unit tests must test the fetching of appropriate datasets, and UI tests on the links and scroll completed.
- Visually appealing table displayed with the correct datasets
- Functional links to search page of the corresponding dataset

Story Point - 5
RIsk - Low
Priority - Medium

**Comment by ds161833** [comment]
there can be settings as: imperical/metric system potentially, graphs theme (if we want to go with that), like maybe default colorcode1, colorcode2 etc.
