### ISSUE TITLE
[Research] - Create a Confluence Page with Research on the possible tools for Computer Vision and Machine Learning based on Requirements

### ISSUE THREAD

**Issue by TiraFire** [Data-Boom/SOEN490#158]
As a Developer, I would like to know the tools that are available for computer vision and machine learning features, as well as use the Stakeholders requirements to determine which ones are best for our case.

Description:
Learn what CV and ML tools have which features to find which one will serve our purposes the best. Make a confluence page to show the research done into these tools, as well as document the gathered requirements from Kiyanda and make the connection to each of these tools.

- [x] Create a Confluence page with the ML and CV tools along with their features
- [x] Determine which ones will be useful based on the requirements gathered from Kiyanda

Acceptance Criteria:
- List of the tools per category
- List of the features that differ between the tools as well as the similar ones
- List of the pros and cons based on reviews per project (in a vague sense)
- Decision on the best candidate for the requirements from Kiyanda

**Comment by TiraFire** [comment]
Research was extensive into the computer vision aspect relating to the detonation cells. There is still a lot of research needed into all the different libraries as well as just the methodology that we will use to find the distance. The overall choice is to obvious reduce the image down to the edges that we can detect using what I found to be the best one "Canny Edge". This detection involves 5 steps : 

1. - Noise reduction;
2. - Gradient calculation;
3. - Non-maximum suppression;
4. - Double threshold;
5. - Edge Tracking by Hysteresis.

Once this is done, the first thought is to use corner detection "Harris corner detection" to find the distance between these corners (essentially the widths).

For more detail, read the confluence page.

https://databoom.atlassian.net/wiki/spaces/DB/pages/222363691/Computer+Vision+Technology+Research

**Comment by TiraFire** [comment]
**To discuss the Acceptance Criteria**
- List of the tools per category
For the idea of computer vision, the most obvious tool to use is OpenCV because it is free and has libraries that can be used to achieve our goal. In terms of libraries, there were the decision to use either Canny edge detector or Sobel Edge Detection.

- List of the features that differ between the tools as well as the similar ones
These are both edge detectors but pros and cons to both
![image](https://user-images.githubusercontent.com/25015601/105791386-fad32d00-5f53-11eb-8ecf-18cf74e4d2ce.png)

The other library is the Harris Corner detection but this is only one option to measure the cell widths. There must be testing done to see if this is a viable solution.

- Decision on the best candidate for the requirements from Kiyanda
The requirement from Kiyanda includes being able to have a list of cell widths from each of these detonation cell images. This requires being able to detect all the cells and their widths. From what I have seen, the edge and corner detection should be able to accomplish this

**Comment by silent-po2** [comment]
With this story having shifted to focus on computer vision, this article is a great starting point for us. As pointed out, edge detection is something we definitely need to read more on, but this is for a future sprint. 
A minor nitpick I would point out is that "computationally more efficient as Canny" is written twice and that doesn't make sense. I assume it was meant to say _than_ instead of _as_. Other than that, this article achieves what we set out to do with this story.
