### ISSUE TITLE
User Details and Settings

### ISSUE THREAD

**Issue by JeremiahTee** [Data-Boom/SOEN490#16]
As a user, I would like to access my user details settings.

**Description**: The user will be able to access and edit the details settings.

**Tasks Involved:**

- [x] Frontend
- [x] Backend
- [x] Unit Test
- [x] UI Test

Mockup Image or link to Mockup:

To Come.

Story Point - TBD
RIsk - TBD
Priority - TBD

**Comment by Mehrdadmaskull** [comment]
This issue will be closed as the UI tests for this part has been done in #243
