### ISSUE TITLE
[Research] - How to Handle TypeORM Migrations & Synchronization on Azure DB

### ISSUE THREAD

**Issue by TiraFire** [Data-Boom/SOEN490#165]
As a developer, I would like to have a document on confluence with coding practices to follow when dealing with TypeORM & mySQL Azure Database.

Description:
This research document will go into the details of how to handle migrations (for new changes to tables in development & productions) and synchronization with respect to TypeORM, how/does this change when dealing with a cloud based database Azure (if there are any specific practices), how do we track changes to the tables, how do we use version control on it, what kind of configurations should we follow for production and any other relevant information.

Acceptance Critieria:
- Well outlined and informative confluence page answering the questions/topics within the description

**Comment by silent-po2** [comment]
Confluence report link: https://databoom.atlassian.net/wiki/spaces/DB/pages/199327747/Report+TypeORM+Synchronization+and+Migrations+165
