### ISSUE TITLE
Research Page [References: #18 #19]

### ISSUE THREAD

**Issue by JeremiahTee** [Data-Boom/SOEN490#17]
As a User, I would like to have a page dedicated to the research portion of the database.

**Description**: 
To understand this page, there are two main components. There is the PNG upload of a data cell that is to be given for analysis to determine the widths of the cells. This givens an array of data cell widths back along with their frequency. The second portion concerns the research papers. The research papers can be uploaded to have their information extracted to be turn into a new dataset for the database.

**Tasks Involved:** 

Each Task includes the frontend, and UI tests. For now, the backend and unit tests are not part of this story.

- [x] Data Cell Analysis #18 
- [x] Research Paper Analysis #19 

The mockups can be found inside the tasks

**Acceptance Criteria**
- A person can submit a PNG file of a data cell (regular or irregular) and have the data widths submitted back (with the option to complete a dataset form to upload to the database)
- A person can submit a research paper and have a dataset given back (with the option to upload to the database)

Story Point - 5
Risk - Highs
Priority - High

**Comment by TiraFire** [comment]
This can be closed now that the UI tests are done
