### ISSUE TITLE
Setup Environment for Development, CI & Testing

### ISSUE THREAD

**Issue by GD-Dheer** [Data-Boom/SOEN490#2]
This EPIC will contain complete setup:

- Development environment will be setup in the following manner:

1) Frontend will be in React
2) Backend will be setup with NodeJS using Express Framework. Language for development will be Typescript
3) DB will be mysql

ML Module: TBD

Computer Graphics Module: TBD

Complete environment will be dockerized for ease of setup 

Testing Structure: TBD

CI Builds: TBD

**Comment by ds161833** [comment]
https://www.infoq.com/articles/typescript-mysql/

**Comment by ds161833** [comment]
what do we mean by Computer Graphics Module?

**Comment by TiraFire** [comment]
It seems as though the issues linked to this issue were closed, the modules for the ML and Computer vision will be discussed in sprint 7, the issue in this case can be closed
