### ISSUE TITLE
[Database] "Point in Time" Restore - See how to create backup of Azure DB

### ISSUE THREAD

**Issue by TiraFire** [Data-Boom/SOEN490#201]
As a developer, I would like to have an option to revert back to a specific moment in time to restore the database.

**Description** 
Since there will be uploads and modifications within the database, an option to restore a point in time for the database can be extremely helpful.

**Tasks**
- [x] Research into Azure and document how to create said "points in time"
- [x] Create a point in time of our database that we can restore (Test purpose = 10/01/2021)

Acceptance Criteria
- Document describing the process to save this point in time and how to restore it
- Saved point in time (the test purpose value)

**Comment by silent-po2** [comment]
Confluence report link: https://databoom.atlassian.net/wiki/spaces/DB/pages/192544802/Database+Backup+and+Restore+201
