### ISSUE TITLE
[Frontend] - Successful sign up message

### ISSUE THREAD

**Issue by ds161833** [Data-Boom/SOEN490#207]
Currently there is no feedback on the sign up page on whether or not the sign up was successful, you just hit sign up, it gets processed but the user has no clue how it went. Also once the user has signed up successfully they should be redirected to the login page.

Acceptance criteria:
When the sign up is successful display "Sign up for {email} was successful"
**Then redirect to the login page**

**Comment by GD-Dheer** [comment]
> Currently there is no feedback on the sign up page on whether or not the sign up was successful, you just hit sign up, it gets processed but the user has no clue how it went. Also once the user has signed up successfully they should be redirected to the login page.
> 
> Acceptance criteria:
> When the sign up is successful display "Sign up for {email} was successful"
> **Then redirect to the login page**

Need to add detailed descriptions for these stories following the template of our previous stories @ds161833
