### ISSUE TITLE
[Frontend] - Store cookie until a preset date if the user has selected Remember me option

### ISSUE THREAD

**Issue by ds161833** [Data-Boom/SOEN490#209]
There is an 'expires' property supplied together with httpOnly, that expires specifies the date of cookie expiration. If BE receives loginInfo with Remember me set to true, then it should set this 'expires' property to UTC.now + N days. N could be 30 for example. If remember me is not set to true, do not assign the expires property at all, meaning leave it empty, that will force the cookie to be removed on browser close:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies
![image.png](https://images.zenhubusercontent.com/5e288bb3a6b24a05dc3f9ac7/cccc2452-55e5-4e00-8c2d-bb67b18118f4)

**Comment by GD-Dheer** [comment]
> There is an 'expires' property supplied together with httpOnly, that expires specifies the date of cookie expiration. If BE receives loginInfo with Remember me set to true, then it should set this 'expires' property to UTC.now + N days. N could be 30 for example. If remember me is not set to true, do not assign the expires property at all, meaning leave it empty, that will force the cookie to be removed on browser close:
> https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies
> ![image.png](https://camo.githubusercontent.com/f493ee2892f4b11499789cfa527d4358b3602ada5cc437573f9a6825ed9a4581/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3565323838626233613662323461303564633366396163372f63636363323435322d353565352d346530302d386332642d626236376231383131386634)

JWT expires after a certain time frame. We shouldn't set an expire time for the cookie because the cookie contains the JWT and not the user info (for the remember me). If the JWT is expired then we need the user to login again. 

If you want to use this feature then youll have to save the email only in the session

**Comment by ds161833** [comment]
we decided we're not doing this task
