### ISSUE TITLE
[Frontend] - Select Variables and their Units to View in Graph Feature

### ISSUE THREAD

**Issue by TiraFire** [Data-Boom/SOEN490#212]
As a User, I would like to be able to change which variables of a datasets I see on an axis as well as which units.

**Description** :
Within a dataset, there are multiple variables (Cell width, initial temperature, etc).  The goal of this feature is to allow the user to decide which of these variable will display on which axis. One of the issues is deciding how to deal with the unshared variables between the datasets. 
For example, if the user would like to display the cell width on the X axis but Dataset-2 does not have values for this variable, how would it be displayed?
The solution is to create a table similar to the one below: 
Following Datasets are omitted because they do not have “X” variable 
|-----------------------------------------------------------------------------------------------------|
|       |
| Dataset 1                                                                                                                       |
| Dataset 6 *                                                                                                                    |

Following Datasets are omitted because they do not have “Y” variable     
|   -------------------------------------------------------------------------------------------------   |
| Dataset 4                                                                                                                       |
| Dataset 6 *                                                                                                                    |
|*  A dataset may be missing both the X and Y variable|

The other issue is the selection of units for the variables. This requires methods to convert the units (if libraries do not exist) to the appropriate units. The units available for each variable should be predetermined (specific units for specific variables).

Pressure: kPa, MPa, GPa, bar, atm
Temperature: K (Kelvin), oC (celsius)
Velocity: km/s, mm/mu.s, m/s
Cell size, cell length (any physical lenght): mm, cm, m
density: kg/m^3, g/cc
specific volume: cc/g, m^3/kg

Conversion of the units will happen in the backend.

**Mockup** 
![image](https://user-images.githubusercontent.com/25015601/104634104-2dd11300-566e-11eb-944a-fb652d508a4d.png)
![image](https://user-images.githubusercontent.com/25015601/104634850-28c09380-566f-11eb-890e-426e0be72eb7.png)

**Acceptance Criteria**
- Must display which datasets are not shown on the graph (which variable they lack)
- Must change the axis titles when a new one is selected
- Must show the appropriate units and convert 
- Must update the graph datapoints
- Must find a way to keep the dataset information in the frontend for these changes (Do not ask the database each time the user changes a variable)

**Comment by cbkiyanda** [comment]
List a variable if I'm missing it in here:
Pressure: kPa, MPa, GPa, bar, atm
Temperature: K (Kelvin), oC (celsius)
Velocity: km/s, mm/mu.s, m/s
Cell size, cell length (any physical lenght): mm, cm, m
density: kg/m^3, g/cc
specific volume: cc/g, m^3/kg

**Comment by TiraFire** [comment]
initial pressure
initial temperature
equivalence ratio
percent n2
cell width
percent air
percent steam
percent ar
percent he
percent co2
percent He and CO2
percent He and H2O
dilution ratio
percent c2h4
percent h2
percent c2h2
percent co
h2s mole fraction
cell length
percent cf3h
percent cf4
critical tube diameter
critical charge
critical energy
cylindrical critical energy
percent additive
minimum tube diameter

**Comment by cbkiyanda** [comment]
`*` pressure: same as pressure
`*` temperature: same as temperature
percent `*` : it's a percentage, so % (0-100) or fraction (0-1)
equivalence ratio: it's a pure ratio, so unitless
dilution ratio: unitless
cell width, cell length: units of length, same as cell size
`*` mole fraction: unitless
critical tube diameter, minimum tube diameter: units of length

**Comment by cbkiyanda** [comment]
For the following:
* critical charge
* critical energy
* cylindrical critical energy
what are the units in there right now?

**Comment by lposo** [comment]
Critical Energy uses joules, critical charge uses "kg tetryl". Unsure about cylindrical crticial energy, but I assume it's also joules.

**Comment by TiraFire** [comment]
Due to a decision to create a user specific solution to the conversion of units, this will be dealt in another sprint to give us more time to create this solution.

The other issue is the selection of units for the variables. This requires methods to convert the units (if libraries do not exist) to the appropriate units. The units available for each variable should be predetermined (specific units for specific variables).

Pressure: kPa, MPa, GPa, bar, atm
Temperature: K (Kelvin), oC (celsius)
Velocity: km/s, mm/mu.s, m/s
Cell size, cell length (any physical lenght): mm, cm, m
density: kg/m^3, g/cc
specific volume: cc/g, m^3/kg
percent * : it's a percentage, so % (0-100) or fraction (0-1)
equivalence ratio: it's a pure ratio, so unitless
dilution ratio: unitless
cell width, cell length: units of length, same as cell size
* mole fraction: unitless
critical tube diameter, minimum tube diameter: units of length
