### ISSUE TITLE
[Backend] - Admin/Approvals API

### ISSUE THREAD

**Issue by TiraFire** [Data-Boom/SOEN490#214]
As a developer, I would like an API that validates and changes the approval status of a submitted dataset and/or edits a submitted dataset.

**Description** 

An admin has the capability to approve/reject datasets as well as add comments. This is a feature ONLY for admins. Therefore, there needs to be a way to check whether the user is an admin, and react accordingly (such as giving them access to the page to approve/reject and modify datasets). This API should change the approved status of a data set and enter relevant comments about the dataset into its DB row as well as let the admin modify the dataset selected.

Additional Notes:
- If an admin rejects a dataset then it must also be deleted from the DB
- When an admin raises a flag, a message X must be sent to the uploader indicating that their dataset needs editing with message X

2 types of comments need to be saved. 
1 ) Comment describing the dataset - (Kiyanda: I love this dataset. Its my favourite dataset). This comment is appended to the existing dataset comment (found in the actual dataset)
2) Comment regarding the status of the submitted dataset (incorrect entry) 

**Acceptance Criteria**
- Allow only admins to access the approval/reject page
- Allow admins to modify/edit datasets
- Allow admin to approve/reject the dataset
- Allow admin to comment on a dataset
- Allow admin to flag an incorrect submission

Verify if multiple apis need to be created to support these different commands

**Comment by silent-po2** [comment]
To give an update on this issue: the functionality for this is complete and operational. We will be doing a number of tests tomorrow to ensure it is 100% good to go, but thus far everything is working as intended
