### ISSUE TITLE
"Upload this File" cannot find a property of an undefined file.

### ISSUE THREAD

**Issue by TiraFire** [Data-Boom/SOEN490#233]
**Describe the bug**
When the button "Upload this File" is clicked inside the "File Upload" page, if there is no file chosen, it produces an error due to trying to find a property of an undefined file.

**To Reproduce**
1. Navigate to the File Upload page
![image](https://user-images.githubusercontent.com/25015601/104855187-50b32f80-58d9-11eb-8f0f-5cbfa4c4e334.png)

2. Click "UPLOAD THIS FILE!"
![image](https://user-images.githubusercontent.com/25015601/104855194-5872d400-58d9-11eb-8a89-6475b456de2d.png)

**Expected behavior**
There should either be a window that displays to the user that they must select a file, or not allow the button be pressed until a file is chosen.

**Comment by TiraFire** [comment]
With the relocation of this feature #290 , this bug should only be fixed if it is quick. Otherwise, it will disappear with the new story

**Comment by ds161833** [comment]
Unable to reproduce the bug, maybe it got fixed after one of the Form Upload clean ups
