### ISSUE TITLE
[Backend] - Date of Birth returned to frontend is incorrect on Profile Page

### ISSUE THREAD

**Issue by GD-Dheer** [Data-Boom/SOEN490#246]
Describe the bug
After logging into account and navigating to profile page the DOB format is incorrect as it includes some time. Likely it is stored as Date

To Reproduce
1) Log into Account
<img width="560" alt="Screen Shot 2021-01-20 at 5 25 42 PM" src="https://user-images.githubusercontent.com/25235293/105248529-8a3ba300-5b44-11eb-8485-97590c508bc6.png">

2) Navigate to profile page
<img width="233" alt="Screen Shot 2021-01-20 at 5 26 23 PM" src="https://user-images.githubusercontent.com/25235293/105248576-9fb0cd00-5b44-11eb-8370-034fa5d47ed6.png">

3) See DoB in incorrect format
<img width="301" alt="Screen Shot 2021-01-20 at 5 26 48 PM" src="https://user-images.githubusercontent.com/25235293/105248605-b0614300-5b44-11eb-8edd-83603b0aad50.png">

Expected Behaviour:
Date of birth presented without time format

**Comment by TiraFire** [comment]
The DOB will be removed per stakeholders requirements so this bug shouldnt be touched.

**Comment by TiraFire** [comment]
#282 Will fix this since it will remove it

**Comment by ds161833** [comment]
Bug gets no estimation points, because it is no longer relevant, since the DOB is being removed from user's details
