### ISSUE TITLE
[Frontend] Graph search by subcategory and year is allowed, yields different results

### ISSUE THREAD

**Issue by JeremiahTee** [Data-Boom/SOEN490#271]
**Describe the bug**
When a user wants to search for a subcategory, if there is no category given, it will not use this search criteria. There should be a way to not allow the user to choose a subcategory is no category is given. It works as instructed but the UI needs to make this not an option

**To reproduce**
1. Go to the Graph page page
2. Click on "Add dataset"
3. Click on Subcategory list and choose "width" 
4. Click on Year and specify "1980"
![image](https://user-images.githubusercontent.com/6520150/105660845-f5191100-5e99-11eb-8980-e04c4e683629.png)
5. Click Search Database

This search is processed and 4 datasets are returned. The catch is that they have different subcategories!

![image](https://user-images.githubusercontent.com/6520150/105660888-09f5a480-5e9a-11eb-896d-8b926a3ea559.png)

**Expected behaviour**
This search should not be allowed as searching by subcategory alone returns different datasets. A subcategory AND a category should be specified. 
When searching for "subcategory" alone, this error message pops up:
![image](https://user-images.githubusercontent.com/6520150/105660775-c9962680-5e99-11eb-8b45-9a6b57638f0f.png)
This error message should pop up as well when reproducing the steps listed.

*Notes*
This bug was discovered in PR #270

**Comment by GD-Dheer** [comment]
Will be handled in sprint 8

**Comment by silent-po2** [comment]
As of the recent PR which overhauled categories, this has been fixed, as subcategory is now a valid search term in and of itself.
