### ISSUE TITLE
[Backend] - Develop CRUD API for dimensions and unit  (returning units and their conversion formulas)

### ISSUE THREAD

**Issue by GD-Dheer** [Data-Boom/SOEN490#286]
As a developer i want to be able to `GET /api/v1/dimensions` <- which should return all dimensions and units that are being stored in the db. The endpoint should also accept a query parameters, for now, just an array of dimension ids to fetch from db

**Description**
We need a way to enforce a standard on dimensions and units for users, so that we can easily convert units, and display units represented differently on the same page.

API definition:
POST /api/v1/dimensions <- add an IDimension FE does not provide dimensionId, all units inside this dimension are new units, return dimension ID
PUT /api/v1/dimensions <- update an IDimension, id is provided, some units will have an id that means they have been created before therefore they should be updated, some units will not have an id -> should be created.
DELETE /api/v1/dimensions/:dimensionId completely remove this dimension and all of its units.

Only superuser should be able to post, put and delete. Get should not have a constraint.

interface IDimension {
  name: string,
  id?: number,
  baseUnitId: number,
  units: IUnit[]
}

interface IUnit {
  name: string,
  id?:number
  conversionFormula: string,
}

**Acceptance Criteria**
- only a dimension with a name and at least one unit (that also happens to be the base unit) can be posted/put, add validations. baseUnitId
-

**Comment by ds161833** [comment]
This API should support CRUD on this model:
interface IQuantity {
  name: string,
  id: string,
  baseUnit: IUnit,
  units: IUnit[]
}

interface IUnit {
  name: string,
  conversionFunction: string,
}

there are also UI changes + new page that are needed to support the CRUD on units and categories with materials etc...

**Comment by Arrow105** [comment]
Name will be dropped as a field for it is not required as per stakeholder discussion. Discussion is still required, in particular regarding the API, as the proposed CRUD will not meet all the stakeholder/DB requirements.
