### ISSUE TITLE
[Frontend] - Relocate the Paper Analysis and File Upload into the Manual Upload Page (Dataset Upload)

### ISSUE THREAD

**Issue by TiraFire** [Data-Boom/SOEN490#290]
As a user, I want all the ways to upload a dataset in the same page.

**Description :**
As of now, the file upload and the pdf paper upload are in there own pages. This should move those options to the dataset Upload page.

**Mockup :**
To come

Acceptance Criteria
This should retain all the functionality of the file upload
This should allow drag and drop for both the PDF and JSON

**Comment by ds161833** [comment]
closing as a duplicate of a finished story
