### ISSUE TITLE
[Frontend] - Allow downloading of datasets in other formats

### ISSUE THREAD

**Issue by TiraFire** [Data-Boom/SOEN490#295]
As a user, I want to be able to download datasets in different formats.

**Description** 
The platform should allow users to download their datasets in CSV, XLS...

**Tasks**
- [ ] Task 1: Download option for {FILETYPE 1}
- [ ] Task 2: Download option for {FILETYPE 2}

**Acceptance Criteria**
Datasets can be opened in newly downloaded file

**Comment by ds161833** [comment]
duplicate
