### ISSUE TITLE
Web Development Environment Setup

### ISSUE THREAD

**Issue by GD-Dheer** [Data-Boom/SOEN490#3]
Development environment will be setup in the following manner:

- Frontend will be in standard React
- Backend will be setup with NodeJS using Express Framework. Language for development will be Typescript
- DB will be mysql

Web ENV will be dockerized. Architecture TBD

**Comment by Mehrdadmaskull** [comment]
In this story, we are aiming to have all team members to have the dev environments set up.

**Comment by Mehrdadmaskull** [comment]
Thanks @GD-Dheer for working on the hot-loading of the front/back-end
We weren't able to complete the setup on all members' systems but we tested on both Mac and Windows operating systems and we only need to make sure everyone has access to the dev environment before we proceed with the next sprint.

Story is good to be closed
