### ISSUE TITLE
[Bug] DatasetUploadForm does not set category or subcategory when setting an initial dataset

### ISSUE THREAD

**Issue by lposo** [Data-Boom/SOEN490#300]
**Describe the bug**
When using the manual dataset upload form, you can set the initial values to be a dataset of type IDatasetModel. This will map out all the values of the form to be equal to those of the dataset selected. However, category and subcategory are left blank.

**To Reproduce**
![image.png](https://images.zenhubusercontent.com/5e209f09aaf6ad68610604cb/8ced8575-a503-43b2-a8f7-ed0e8b7f534d)
- Set a dataset as the initial dataset for the DatasetUploadForm

**Expected behavior**
The form fills out using all the information found in the dataset.

**Comment by ds161833** [comment]
this will be fixed once we completely implement categories and subcategories funcitonality

**Comment by silent-po2** [comment]
To update this issue, the bug still persists. With a file upload, a category is now properly selected, but a subcategory is not despite both a category and subcategory ID being provided when they exist.

**Comment by GD-Dheer** [comment]
Handled with PR #528
