### ISSUE TITLE
AT-1 Graph Feature Acceptance Test with Changes

### ISSUE THREAD

**Issue by TiraFire** [Data-Boom/SOEN490#318]
##### Here there are all tests needed for this feature

Graph epic consists of sub-stories that were mostly implemented

Tests | Variable Inputs | Expected Result | Status
-- | -- | -- | --
Access the home page | Launch the website on localhost | Homepage is shown |  
Access the graph page | Navigate to the graph page from the side menu | The graph page appears |  
Find dataset to add to graph | Click “ADD DATASET TO GRAPH” button, search for some values, like “year = 1990” and click “SEARCH DATABASE” | A search form will appear, after searching for values a list of Datasets will be displayed on the form |  
Add datasets to graph | Select one or more datasets from the list shown and click  “ADD TO GRAPH” | Datasets will be added to graph |  
Change the display settings | Click “Settings” button, choose “X Variable” and “Y variable” to be compared and shown on graph | Datasets will be shown on the graph according to the X and Y variables selected |  
Hide/Show dataset on graph | Click on the “eye” icon on a specific dataset to hide it, clicking again will show the dataset again | A specific dataset will be hidden or shown |  
Remove a dataset from the graph | Click on the “Trash bin” icon to remove a dataset from the graph | A specific dataset will be removed from the graph |  
Change the scaling of the graph, and return it to default view | Use the scales on the top and right sides to change the X and Y scales on the graph respectively, clicking on the “-” blue circle in the top right corner of the graph will return the scales to default | The scales of the graph will change |

**Comment by cbkiyanda** [comment]
Tests | Variable Inputs | Expected Result | Status
-- | -- | -- | --
Access the home page | Launch the website on localhost | Homepage is shown |  accepted
Access the graph page | Navigate to the graph page from the side menu | The graph page appears |   accepted
Find dataset to add to graph | Click “ADD DATASET TO GRAPH” button, search for some values, like “year = 1990” and click “SEARCH DATABASE” | A search form will appear, after searching for values a list of Datasets will be displayed on the form |  accepted
Add datasets to graph | Select one or more datasets from the list shown and click  “ADD TO GRAPH” | Datasets will be added to graph |  accepted
Change the display settings | Click “Settings” button, choose “X Variable” and “Y variable” to be compared and shown on graph | Datasets will be shown on the graph according to the X and Y variables selected |  accepted
Hide/Show dataset on graph | Click on the “eye” icon on a specific dataset to hide it, clicking again will show the dataset again | A specific dataset will be hidden or shown |  accepted
Remove a dataset from the graph | Click on the “Trash bin” icon to remove a dataset from the graph | A specific dataset will be removed from the graph |  accepted
Change the scaling of the graph, and return it to default view | Use the scales on the top and right sides to change the X and Y  scales on the graph respectively, clicking on the “-” blue circle in the  top right corner of the graph will return the scales to default | The scales of the graph will change |  accepted
