### ISSUE TITLE
AT-3 Sign Up/Log In/Log Out

### ISSUE THREAD

**Issue by TiraFire** [Data-Boom/SOEN490#319]
This acceptance test tests the features to sign up, log in, and log out

Tests | Variable Inputs | Expected Result | Status
-- | -- | -- | --
Access the home page | Launch the website on localhost | Homepage is shown |  
Navigate to Log in page | Click “LOG IN” button in the top right corner to navigate to the login page | Login page is shown |  
Sign up for a new account | Click “Don’t have an account? Sign Up” link to navigate to sign up page | The Sign up page form will be displayed |  
Fill the information and sign up | Fill out all the required fields and then click “SIGN UP” button | The account will get created and the user will get rerouted to Log in with the new account |  
Log in with new account | Fill in the email address and password of the newly created account and click “LOG IN” | The user will be logged in |  
Sign Out | Click “SIGN OUT” button on the top right corner to sign out of your account | The user will get signed out |

**Comment by cbkiyanda** [comment]
Tests | Variable Inputs | Expected Result | Status
-- | -- | -- | --
Access the home page | Launch the website on localhost | Homepage is shown |  accepted
Navigate to Log in page | Click “LOG IN” button in the top right corner to navigate to the login page | Login page is shown |  accepted
Sign up for a new account | Click “Don’t have an account? Sign Up” link to navigate to sign up page | The Sign up page form will be displayed |  accepted
Fill the information and sign up | Fill out all the required fields and then click “SIGN UP” button | The account will get created and the user will get rerouted to Log in with the new account |  accepted. Note: Get rid of birth date!
Log in with new account | Fill in the email address and password of the newly created account and click “LOG IN” | The user will be logged in |  accepted
Sign Out | Click “SIGN OUT” button on the top right corner to sign out of your account | The user will get signed out |  accepted

Notes: 

* Get rid of the "Hello, " part. I hate computer systems that try to anthropomorphize themselves. They're computers. Deal with it.
* When logged in, there needs to be more space between the name and the "Log out" button to be visually pleasing.

Bug:
* Navigate to page, click "log in", sign up for new account, log in with new account, log out.
* Once logged out, open the left-hand menu, click the still visible "profile" option. 
* You will get a "Unhandled rejection (TypeError) error. (See second screenshot.)

![Screenshot from 2021-02-02 21-56-39](https://user-images.githubusercontent.com/454918/106691601-c7bb1a00-65a1-11eb-8d99-db1368b25c86.png)


![Screenshot from 2021-02-02 21-54-24](https://user-images.githubusercontent.com/454918/106691352-5bd8b180-65a1-11eb-97ad-3506ded09342.png)

**Comment by TiraFire** [comment]
#282 will fix first issue
#374 is for the bug report
