### ISSUE TITLE
AT-4 Account Information

### ISSUE THREAD

**Issue by TiraFire** [Data-Boom/SOEN490#320]
Tests | Variable Inputs | Expected Result | Status
-- | -- | -- | --
Access the home page | Launch the website on localhost | Homepage is shown |  
Navigate to Log in page | Click “LOG IN” button in the top right corner to navigate to the login page | Login page is shown |  
Log in to your account | Enter the email address and password in the required fields and when done click “LOG IN” | Redirected to Home page and the user is signed in |  
Navigate to Profile page | Navigate to the profile page from the side menu | The profile page appears |  
Edit your profile | Click “EDIT PROFILE” button to edit some personal information | A list of editable information will be shown |  
Save your new settings | Click “SAVE” after editing or “CANCEL” to cancel your changes | The settings will be saved and updated or cancelled based on the choice |  
Sign Out | Click “SIGN OUT” button on the top right corner to sign out of your account | The user will get signed out |  

### Demo Steps

**Comment by cbkiyanda** [comment]
Tests | Variable Inputs | Expected Result | Status
-- | -- | -- | --
Access the home page | Launch the website on localhost | Homepage is shown |  accepted
Navigate to Log in page | Click “LOG IN” button in the top right corner to navigate to the login page | Login page is shown |  accepted
Log in to your account | Enter the email address and password in the required fields and when done click “LOG IN” | Redirected to Home page and the user is signed in |  accepted
Navigate to Profile page | Navigate to the profile page from the side menu | The profile page appears |  failed. I get savedGraphState.reverse is not a function (see screenshot)
Edit your profile | Click “EDIT PROFILE” button to edit some personal information | A list of editable information will be shown |  blocked by failure
Save your new settings | Click “SAVE” after editing or “CANCEL” to cancel your changes | The settings will be saved and updated or cancelled based on the choice |  blocked by failure
Sign Out | Click “SIGN OUT” button on the top right corner to sign out of your account | The user will get signed out |  blocked by failure

OS ubuntu 20.04.1 LTS focal
firefox 85.0

![Screenshot from 2021-02-02 22-04-29](https://user-images.githubusercontent.com/454918/106692544-ad357080-65a2-11eb-945b-05bc766ab5df.png)

**Comment by cbkiyanda** [comment]
Correction. Once navigating back to the home page, I can click the sign out button.

Tests | Variable Inputs | Expected Result | Status
-- | -- | -- | --
Sign Out | Click “SIGN OUT” button on the top right corner to sign out of your account | The user will get signed out | accepted
-- | -- | -- | --

**Comment by cbkiyanda** [comment]
Retesting

Tests | Variable Inputs | Expected Result | Status
-- | -- | -- | --
Access the home page | Launch the website on localhost | Homepage is shown | accepted
Navigate to Log in page | Click “LOG IN” button in the top right corner to navigate to the login page | Login page is shown | accepted
Log in to your account | Enter the email address and password in the required fields and when done click “LOG IN” | Redirected to Home page and the user is signed in | accepted
Navigate to Profile page | Navigate to the profile page from the side menu | The profile page appears | works, bug not triggered.
Edit your profile | Click “EDIT PROFILE” button to edit some personal information | A list of editable information will be shown | accepted
Save your new settings | Click “SAVE” after editing or “CANCEL” to cancel your changes | The settings will be saved and updated or cancelled based on the choice | accepted
Sign Out | Click “SIGN OUT” button on the top right corner to sign out of your account | The user will get signed out | accepted

**Comment by TiraFire** [comment]
#374 Will fix the bug mentioned
