### ISSUE TITLE
AT-5 Saving a Graph

### ISSUE THREAD

**Issue by TiraFire** [Data-Boom/SOEN490#321]
Tests | Variable Inputs | Expected Result | Status
-- | -- | -- | --
Access the home page | Launch the website on localhost | Homepage is shown |  
Navigate to Log in page | Click “LOG IN” button in the top right corner to navigate to the login page | Login page is shown |  
Log in to your account | Enter the email address and password in the required fields and when done click “LOG IN” | Redirected to Home page and the user is signed in |  
Access the graph page | Navigate to the graph page from the side menu | The graph page appears |  
Find dataset to add to graph | Click “ADD DATASET TO GRAPH” button, search for some values, like “year = 1990” and click “SEARCH DATABASE” | A search form will appear, after searching for values a list of Datasets will be displayed on the form |  
Add datasets to graph | Select one or more datasets from the list shown and click  “ADD TO GRAPH” | Datasets will be added to graph |  
Change the display settings | Click “Settings” button, choose “X Variable” and “Y variable” to be compared and shown on graph | Datasets will be shown on the graph according to the X and Y variables selected |  
Save the graph in its current state | After editing and modifying the graph fill the “Graph Name” field with a name of your choosing and click on “SAVE GRAPH” button | A message will be displayed confirming the success of saving the graph |  
Access the profile page | Navigate to the profile page from the side menu | The profile page appears |  
Access the view favourites tab | Navigate to the second tab called “VIEW FAVOURITES” and click on it | The saved Graphs page appears |  
Display the saved graph | Find your recently saved graph by the name and click on it | Reroute to graph page and the graph will be displayed in its saved condition |

**Comment by cbkiyanda** [comment]
Tests | Variable Inputs | Expected Result | Status
-- | -- | -- | --
Access the home page | Launch the website on localhost | Homepage is shown |  accepted
Navigate to Log in page | Click “LOG IN” button in the top right corner to navigate to the login page | Login page is shown |  accepted
Log in to your account | Enter the email address and password in the required fields and when done click “LOG IN” | Redirected to Home page and the user is signed in |  accepted
Access the graph page | Navigate to the graph page from the side menu | The graph page appears |  accepted
Find dataset to add to graph | Click “ADD DATASET TO GRAPH” button, search for some values, like “year = 1990” and click “SEARCH DATABASE” | A search form will appear, after searching for values a list of Datasets will be displayed on the form |  accepted
Add datasets to graph | Select one or more datasets from the list shown and click  “ADD TO GRAPH” | Datasets will be added to graph |  accepted
Change the display settings | Click “Settings” button, choose “X Variable” and “Y variable” to be compared and shown on graph | Datasets will be shown on the graph according to the X and Y variables selected |  accepted
Save the graph in its current state | After editing and modifying the graph fill the “Graph Name” field with a name of your choosing and click on “SAVE GRAPH” button | A message will be displayed confirming the success of saving the graph |  accepted
Access the profile page | Navigate to the profile page from the side menu | The profile page appears |  accepted
Access the view favourites tab | Navigate to the second tab called “VIEW FAVOURITES” and click on it | The saved Graphs page appears |  accepted
Display the saved graph | Find your recently saved graph by the name and click on it | Reroute to graph page and the graph will be displayed in its saved condition |  accepted
