### ISSUE TITLE
AT - 6 Password Reset

### ISSUE THREAD

**Issue by laithAwad** [Data-Boom/SOEN490#328]
Tests | Variable Inputs | Expected Result | Status
-- | -- | -- | --
Access the home page | Launch the website on localhost | Homepage is shown |  
Navigate to Login page | Click “LOG IN” button in the top right corner to navigate to the login page | Login page is shown |  
Navigate to Forget Password form | Click “Forgot password?” link | The forget password form will pop up |  
Fill the form | Enter the email address associated with the account to recover password then click “FORGOT PASSWORD” button | A notification will confirm an email sent to reset password |  
Find the link to reset password | Navigate to your own email account, find the email from “noreply@databoom.com” , copy and paste the link sent in your browser | New password page is shown |  
Fill out the new password form | Fill out a new password and confirm it then click “RESET PASSWORD” button | A notification will confirm the password is changed |

**Comment by cbkiyanda** [comment]
Tests | Variable Inputs | Expected Result | Status
-- | -- | -- | --
Access the home page | Launch the website on localhost | Homepage is shown |  accepted
Navigate to Login page | Click “LOG IN” button in the top right corner to navigate to the login page | Login page is shown |  accepted
Navigate to Forget Password form | Click “Forgot password?” link | The forget password form will pop up |  accepted
Fill the form | Enter the email address associated with the account to recover password then click “FORGOT PASSWORD” button | A notification will confirm an email sent to reset password |  accepted
Find the link to reset password | Navigate to your own email account, find the email from “noreply@databoom.com” , copy and paste the link sent in your browser | New password page is shown |  accepted
Fill out the new password form | Fill out a new password and confirm it then click “RESET PASSWORD” button | A notification will confirm the password is changed |  accepted

Note: When showing pop-up messages at the bottom of the screen, take out the exclamation marks, etc. Again, this isn't a person, it's a computer.
