### ISSUE TITLE
[UI] - Create Mockup to allow new admins to the platform

### ISSUE THREAD

**Issue by GD-Dheer** [Data-Boom/SOEN490#349]
**Description** 
This task is to create a mockup that will show how we plan to implement the UI for Admin creation. The UI must have a way to 

1. View all the admins.
2. Have a proper choice of how to add a new admin
3. Show where this will be located in terms of the website
4. Display any of the prompts that could be appear
5. The snackbar messages for both success and failure
6. A way to delete an admin

**Tasks**
- [ ] Task: Create new mockup with Figma or other professional tool

**Acceptance Criteria**
- Deliverable mockup attached to the issue
- Make sure there are descriptions to the mockups if they need any
**UPDATE** here is a wip of a mockup for the page, will add a delete confirmation https://www.figma.com/file/4dELUUuDxeQeSeQMMhVOjP/Getting-somewhere?node-id=0%3A1

**Comment by ds161833** [comment]
Mockup was completed and added to the issue description
