### ISSUE TITLE
[PO] - Describe data file formats [References #9]

### ISSUE THREAD

**Issue by cbkiyanda** [Data-Boom/SOEN490#356]
txt
json
csv
xls
etc

**Comment by cbkiyanda** [comment]
upload and download?

**Comment by TiraFire** [comment]
@cbkiyanda Still waiting on this

**Comment by cbkiyanda** [comment]
json should be the same json format used for upload.

**Comment by cbkiyanda** [comment]
txt and csv are the same format (since csv is just text)

Two blocks of data
Block 1: metadata
Block 2: data with headers

Block 1: metadata, each line starting with '#'
type of dataset, publication details (source), material, etc
add two lines of metadata:
# website-name
# date-of-output in standard format (YYYY-MM-DD-HH-MM-SS or whatever)

Block 2: data
1 line of headers starting with '#'
# variable-name [unit], variable-name [unit], ...
data lines, each number separated by a comma
point1-variable1-value, point1-variable2-value, ...
point2-variable1-value, point2-variable2-value, ...
...

Example:

[txt-csv-sample.txt](https://github.com/Data-Boom/SOEN490/files/5945987/txt-csv-sample.txt)

**Comment by cbkiyanda** [comment]
xls format is pretty much the same as txt, csv. 2 block structure.

* get rid of # signs
* in metadata, put the 'metadata-field-name:' that was in the csv as a cell and the metadata-value in the adjoining cell.
*

**Comment by cbkiyanda** [comment]
[xls-sample.zip](https://github.com/Data-Boom/SOEN490/files/5946021/xls-sample.zip)

**Comment by cbkiyanda** [comment]
**Upload** using csv and txt file should be only for the data portion (I think we discussed this in the last meeting). Just set a header and lines of data:
<variable name> [<unit>], <variable name> [<unit>], <variable name> [<unit>]
data, data, data
data, data, data
data, data, data
[txt_csv_data_upload_sample.txt](https://github.com/Data-Boom/SOEN490/files/5983500/txt_csv_data_upload_sample.txt)
