### ISSUE TITLE
[Backend] - data extraction endpoint should now try to extract the dataset variables into the new model

### ISSUE THREAD

**Issue by ds161833** [Data-Boom/SOEN490#367]
**Description** 
Data extraction endpoint model needs to be updated to return a new altered IDatasetModel with the new Units relations

**Tasks**
- [ ] Task: Update Backend data extraction models to support new category changes

**Acceptance Criteria**
- Data extraction model maps with new IdatasetModel

**Comment by GD-Dheer** [comment]
> **Description**
> Data extraction endpoint model needs to be updated to return a new altered IDatasetModel with the new Units relations
> 
> **Tasks**
> 
> * [ ]  Task: Update Backend data extraction models to support new category changes
> 
> **Acceptance Criteria**
> 
> * Data extraction model maps with new IdatasetModel

Issue was closed with #429
