### ISSUE TITLE
[Task] Modify the Stock image on the home page

### ISSUE THREAD

**Issue by TiraFire** [Data-Boom/SOEN490#377]
Description
Kiyanda will give a new stock image for the home page. This will be an image that he feels is more appropriate for this database.

This is part of the small tasks for the website.

**Comment by GD-Dheer** [comment]
@TiraFire @JeremiahTee Updated needed for this story

**Comment by GD-Dheer** [comment]
Pushed to sprint 9 as stakeholder has not provided specification for this story
