### ISSUE TITLE
[Task] Change the theme colours of the website

### ISSUE THREAD

**Issue by TiraFire** [Data-Boom/SOEN490#378]
Description
The theme colours of the website do not fit well with the concordia logo so Kiyanda would like to change the colours that the website uses. The colours can be discussed with him to find the ones he approves.

This is part of the small tasks for the website.

**Comment by GD-Dheer** [comment]
> Description
> The theme colours of the website do not fit well with the concordia logo so Kiyanda would like to change the colours that the website uses. The colours can be discussed with him to find the ones he approves.
> 
> This is part of the small tasks for the website.

What is the update on this? @TiraFire
