### ISSUE TITLE
[Task] Hide/Unhide All Datasets on graph

### ISSUE THREAD

**Issue by TiraFire** [Data-Boom/SOEN490#385]
**Description**
Include a toggle on the Graphs page to hide or unhide all the datasets.

This is part of the small adjustments that the stakeholder wants.

**Comment by GD-Dheer** [comment]
> **Description**
> Include a toggle on the Graphs page to hide or unhide all the datasets.
> 
> This is part of the small adjustments that the stakeholder wants.

Closed with  #298
