### ISSUE TITLE
[Cell Size Analysis] Measure between the edges (cell size)

### ISSUE THREAD

**Issue by TiraFire** [Data-Boom/SOEN490#389]
As a developer, I would like the measure the distance each cell size with the isolated cell edges.

**Description** 
Once the edges are determined, the cell size must be measured. The measurement will be given for the length of the image and the cell sizes will reflect a percentage of this length for units. An array will be created with these values as well as the location of the cell by a pixel location inside the cell.

**Tasks**
Measure all edges displayed on the image. 
Update: since the user is drawing those edges manually, the measurements between those edges are the points drawn by the user.

**Acceptance Criteria**
The cell sizes are measured
The units are based on given total length of the png with units
The length is given with the location of the cell

**Comment by JeremiahTee** [comment]
After looking into the implementation of Computer Vision and consulting our teacher, we came to the conclusion that it's best to do so with a "human in the loop" solution. The edges are calculated by drawing points supplied by the user. The python script then keeps track of these points and calculates the distances for each edge (lines drawn). 
We proposed the solution to our stakeholder and he approved it. 
The script was included from PR #428
