### ISSUE TITLE
[Mockup] - User Dataset Reviewal Page

### ISSUE THREAD

**Issue by GD-Dheer** [Data-Boom/SOEN490#393]
**Description** 
User should be able to view all their flagged datasets, under the profile view with a tab called flagged datasets

When the user is under this tab, he can see all the flagged datasets listed in a fashion similar to saved graphstates.
He has the option of either editing the dataset and then sending it back to the admin, deleting the dataset or approving the dataset without making any modifications to the dataset.

**Additional Notes**

**Tasks**

- [x] Task: Create Mock reflecting above requirements

**Acceptance Criteria**

**Update** Here is the link to the mockup: https://www.figma.com/file/MmvzMxb3sK8taRBxRalorD/Dataset-Review?node-id=3%3A6
- Link to created mockup with requirements done

**Comment by ds161833** [comment]
Link to the mockup: https://www.figma.com/file/MmvzMxb3sK8taRBxRalorD/Dataset-Review?node-id=3%3A6
