### ISSUE TITLE
Template - Name of Story [References: #0, etc]

### ISSUE THREAD

**Issue by TiraFire** [Data-Boom/SOEN490#4]
As a ________, I would like ________________________________.

**Description:**

**Tasks Involved:**

- [ ]  Task 1
- [ ]  Task 2
- [ ]  Task 3

Mockup Image or link to Mockup:

IMAGE

**Acceptance Criteria**
//here specify what has to be done for the task to be allowed to be closed

**Story Point** - 1, 2, 3, 5, 8, 13.... 
**RIsk** - Low, Med, High
**Priority** - Low, Med, High

**USE THE RIGHT LABELS**

**Comment by ds161833** [comment]
Deleting the issue, since we have proper templates now
