### ISSUE TITLE
Graph page does not display missing datasets when loading a saved graph.

### ISSUE THREAD

**Issue by lposo** [Data-Boom/SOEN490#407]
**Describe the bug**
Users can save the state of a graph for future use, which they can access from their profile. However, when loading a saved graph, it does not display which datasets are missing certain units.

**To Reproduce**
1. Go to the graph page.
2. Load a graph.
3. Click save graph button.
4. Go to user profile page.
5. Go to saved graph.
6. Click on graph previously saved.
7. See that datasets missing is not filled.

**Expected behavior**
The datasets missing field should show which datasets are missing which variables selected.

**Screenshots**
![image](https://user-images.githubusercontent.com/46732530/107891171-e4811700-6eea-11eb-836d-64aad94724d0.png)

**Desktop (please complete the following information):**
 - Windows
 - Google Chrome

**Comment by ds161833** [comment]
todo change this story
