### ISSUE TITLE
Overview of the architecture (Domain model or ER model)

### ISSUE THREAD

**Issue by ds161833** [Data-Boom/SOEN490#42]
As part of this user story @Vatika1 has implemented an ER diagram (can be found in our google docs folder->Documentation->ER Diagram)

SRS outline is being created.

**Comment by ds161833** [comment]
SAD and SRS Outline (Dmit, Vati) tbd

**Comment by Mehrdadmaskull** [comment]
Thanks @ds161833 .

We now have a basic SRS outline that needs more work in the next sprint when we do a thorough evaluation of the project at hand

This story is good to be closed
