### ISSUE TITLE
[Mockup] - Create UI Design for managing modifications of categories & subcategories

### ISSUE THREAD

**Issue by GD-Dheer** [Data-Boom/SOEN490#430]
As super root, I need a page where I can manage categories and subcategories. 

**Description** 
This page will allow the super root to add and alter existing categories and subcategories. 

**Tasks**
- [x] Task: Create Mockup design to show how this page should look

**Acceptance Criteria**
- Link to completed Mockup
**Updated mockup link:** https://www.figma.com/file/MmvzMxb3sK8taRBxRalorD/Dataset-Review?node-id=100%3A705

**Comment by ds161833** [comment]
completed mockup: https://www.figma.com/file/MmvzMxb3sK8taRBxRalorD/Dataset-Review?node-id=100%3A705
