### ISSUE TITLE
Units on Dataset Form Not Showing Correctly

### ISSUE THREAD

**Issue by silent-po2** [Data-Boom/SOEN490#479]
**Describe the bug**
When you add a dimension and unit to a data point column, the unit selected does not appear to be "remembered" or "saved". 

**To Reproduce**
1. Set up a new data set
2. Add a data point with a dimension and unit
3. Re-open the variable information, see the unit is missing as per the screenshot

**Expected behavior**
After entering a dimension and unit, when the name variable field is subsequently opened the unit should be displayed.

**Screenshots**
![image](https://user-images.githubusercontent.com/43076924/110540477-8b289400-80f4-11eb-941f-21010801a408.png)

**Comment by ds161833** [comment]
I fixed this bug in one of the commits, but forgot to lcose the bug
