### ISSUE TITLE
[DB] - host a db "somewhere"

### ISSUE THREAD

**Issue by ds161833** [Data-Boom/SOEN490#49]
I want to be able to host my database somewhere so that the web application, backend and the frontend can access the database.
For now we are going to use local database and once we decide if we want to host it on Concordia servers or on a hosted service, we'll do a migration.
Also the type of the database should be decided, NoSQL vs MySQL

This story includes dockerizing the DB.

**Comment by GD-Dheer** [comment]
Updated the complexity to account for ORM integration

**Comment by ds161833** [comment]
we decided to go with SQL for now, we will see if it really suits our needs like we think

**Comment by GD-Dheer** [comment]
> Updated the complexity to account for ORM integration

Swapping out Sequelize for TypeORM as it has better typescript support
