### ISSUE TITLE
[Mockup] - User Submitted Datasets

### ISSUE THREAD

**Issue by GD-Dheer** [Data-Boom/SOEN490#495]
Description
User should be able to view all their submitted datasets, under the profile view with a tab called my datasets

When the user is under this tab, he can see all the submitted datasets listed in a fashion similar to saved graphstates.

Tasks

- [ ]  Task: Create Mock reflecting above requirements

Acceptance Criteria

- Link to created mockup with requirements done

**Comment by ds161833** [comment]
We would love to spend some time on this, but its too low of a priority
