### ISSUE TITLE
Architecture Diagrams

### ISSUE THREAD

**Issue by Mehrdadmaskull** [Data-Boom/SOEN490#57]
By the end of this sprint, we need to have component and class diagrams

**Comment by TiraFire** [comment]
Component and class diagrams finished, but subject to change during future sprints depending on how the architecture continues.

![image](https://user-images.githubusercontent.com/25015601/96390750-1627e280-1184-11eb-98e4-3047f9f359db.png)


![image](https://user-images.githubusercontent.com/25015601/96390791-3ce61900-1184-11eb-9d32-c2bf16ab051e.png)
