### ISSUE TITLE
[Frontend] & [Backend] File Upload

### ISSUE THREAD

**Issue by Mehrdadmaskull** [Data-Boom/SOEN490#71]
The upload mechanism of the web app needs to accept *.csv files.

- Uploading of the file to the server
- Storing the file somewhere on the server
- Querying the database to pull the data

Specific format for CSV needs to be indicated for this feature to function. @TiraFire @Mehrdadmaskull 

We can iterate through future sprints to accept other file formats

**Comment by GD-Dheer** [comment]
@Mehrdadmaskull Are we supporting txt and csv for this story? There are strict guidelines for uploading a txt, it must follow a specific format for a parser to read it. I started investigating and I think this story is more complex than a 5.... Will need to increase to an 8. Let me know what you think
