### ISSUE TITLE
[Operations] Obtain SSH information & research their native OS (probably linux distribution) for migration

### ISSUE THREAD

**Issue by GD-Dheer** [Data-Boom/SOEN490#72]
- Investigate OS and look at migration options on their OS. Also verify if any upgrades need to be done. OS & other packages

- Research Docker Deployment Options

- Can make a link to a google drive or shared doc to share your research

**Comment by JeremiahTee** [comment]
@TiraFire Sent an e-mail to the IITS people, asking clarifications on:
- Hosting our app on Concordia server (if possible) & how we'll proceed from there
- Once the app is hosted, if there is a way to tunnel in from home to work on it

Will update this issue as soon as we get a reply from IITS.

**Comment by JeremiahTee** [comment]
Investigated the issue - findings can be found at:
https://docs.google.com/document/d/1GWqoSfBWd-ev_OBhq2EzqdlGwJK3dppADQnfqjFd8Gc/edit?usp=sharing

It contains the relevant information that we received from IITS. This issue can be now closed as we - in the near future - will proceed to ask our stakeholder his opinion on how we will deploy.
