### ISSUE TITLE
Create Release Deliverable

### ISSUE THREAD

**Issue by GD-Dheer** [Data-Boom/SOEN490#73]
This includes:
- Adding + cleaning up SRS following template mentioned by prof 
- Begin working on Release Retrospective 
- Start looking into QA reports (Sonar)
- Presentation 
- Graphing feature discussion + video
- UI design
- Architecture Diagrams

Professor mentioned requirements for release in slack. 

Most of this is found in the SRS already it just needs to be cleaned up. Other members will shift to help with this after working on their other features. For now, first 4 points can be worked on.

**Comment by JeremiahTee** [comment]
Filled in most of the release document. The backlog table now reflects all our user stories. Sprint 1,2,3 tables were also filled - Sprint 3 table will need to be updated by tomorrow night as we close all of our remaining issues tomorrow night.
I also included all of our diagrams, wrote on refactoring, design patterns, retrospectives, personas.
I left comments on the document for other team-members to address

TBD:
- Mockups section @laithAwad include the corresponding mockups with the user stories associated
- Unit testing section
- Acceptance test section
- Proof-read / complete rest of the sections

**Comment by Mehrdadmaskull** [comment]
Thanks a lot @JeremiahTee 

I am going to be moving this into done since today is the last day and we will need this story closed for our burndown chart.
