### ISSUE TITLE
[Frontend] D3 Graph Setup

### ISSUE THREAD

**Issue by Mehrdadmaskull** [Data-Boom/SOEN490#79]
The graph needs to be set up using the D3.js library. The graph itself is of type scatter plot with its datasets being a two-dimension array of datapoints.
Research must be done for the features that need to be implemented for the graph and then knowledge-transferred to other members of the team.
The graph needs to receive the datapoints and plot them on the page.

Some examples for the graph can be looked at [here](https://observablehq.com/@d3/gallery) and [here](https://www.d3-graph-gallery.com/index.html)

**Acceptance Criteria:**
- Must be visible and accurate.

**Comment by Arrow105** [comment]
I'm not sure what this PR is aiming to accomplish? It creates a graph page with a title on it and no actual graph. Is this intended?
